### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by HerrBlauzahn**

### CODE REVIEW

**Comment by pomber** [comment]
Is it open source? Can you also add a link to the repo?

**Comment by HerrBlauzahn** [comment]
Technically you could view the code since there is no client-side code, but I plan to put it on GitHub. I'll attach a link to the repo if it's up.

**Comment by HerrBlauzahn** [comment]
Finished. Link to the repo: https://github.com/HerrBlauzahn/Coronavirus

**Comment by pomber** [comment]
Thanks, add it to your changes and I'll merge the pull request.

**Pull request closed without merging**
