### PR TITLE
Add covid-19-telegram project to readme

### PR DESCRIPTION
**Pull request by f2acode**

### CODE REVIEW

**Comment by pomber** [comment]
How do you use it? (I don't use telegram, but the link goes to a readme without much info)

**Comment by f2acode** [comment]
@pomber I get data from the available json, you can see the request [here](https://github.com/f2acode/covid-19-telegram/blob/master/src/data.ts)

**Comment by pomber** [comment]
I mean, when I go to https://github.com/f2acode/covid-19-telegram, I don't see any demo or instructions.

**Comment by f2acode** [comment]
@pomber I see, I've updated my repo with the link of the demo and a short explanation.

**Pull request merged**
