### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Alberto75**
Add my project

If you are adding a new project to the list please follow these rules:

- Add only open source projects
- Make sure the project cite this repo as a data source (with a link) 
- Follow the same order as the rest of the list `- [project-name](your-project-url) ([repo](repo-url)): description`
- Try not to add extra blank lines, it breaks the formatting

### CODE REVIEW

**Comment by Alberto75** [comment]
Excuse me,
did I do something wrong?

**Comment by pomber** [comment]
sorry, do you have the app deployed somewhere I can check it out? couldn't find any link in your readme

**Comment by Alberto75** [comment]
Sorry, only on github(https://github.com/Alberto75/covid-trace)

**Comment by Alberto75** [comment]
Sorry, I've deployd now my app on Firebase
https://covid-trace-6bef4.web.app

**Comment by Alberto75** [comment]
Thanks!!!
Of course thanks for your work on the dataset!!!

Il giorno mar 3 nov 2020 alle ore 22:10 Rodrigo Pombo <
notifications@github.com> ha scritto:

**Pull request merged**
