### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by Subhash3**
I added my project. https://github.com/Subhash3/COVID19_ANALYSIS.

### CODE REVIEW

**Comment by pomber** [comment]
Hey, can you check your changes? Just commit the line adding your project and I'll merge it.

**Comment by Subhash3** [comment]
Hello, I already made a commit. Could you please merge it.

**Comment by pomber** [comment]
Check your commit, it's changing more than it should.

**Comment by Subhash3** [comment]
I apologise for the inconvenience. Due to copying and pasting stuff, I
messed up some parts of the file. I just made a new pull request.

Thank you.

**Pull request closed without merging**
